### ISSUE TITLE
投稿を DB に保存する関数を作成する

### ISSUE THREAD

**Issue by sys-fork** [kokenmma/Arithynet#2]

**Comment by sys-fork** [comment]
Realtime Database とやりとりする際は [JavaScript SDK](https://firebase.google.com/docs/database/web/start?authuser=0&hl=ja#add_the_js_sdk_and_initialize) を利用するにあたって API Key 等が必要になるので，API Key 等は Next.js の .env などに保存しておき，[API Routes](https://nextjs.org/docs/api-routes/introduction) を利用して Hosting 側に処理を飛ばしてそこから Realtime Database にアクセスする形にするのがよさそう．

**Comment by sys-fork** [comment]
.env を個々の開発環境に置くのではなく，GitHub Actions または Hosting の方でデプロイ時に追加することはできますか...？

**Comment by csenet** [comment]
> .env を個々の開発環境に置くのではなく，GitHub Actions または Hosting の方でデプロイ時に追加することはできますか...？

前にやったことがあるのでできると思います

**Comment by csenet** [comment]
`services`以下に実装
